create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  interest text,
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.feedback enable row level security;

revoke all on table public.feedback from anon, authenticated;
grant insert on table public.feedback to service_role;